# Generated by Django 2.2.13 on 2020-08-23 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=150, verbose_name='Invoice Number')),
                ('client_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=300, verbose_name='Project Name')),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount to be Charged')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
